version: '3'

services:
  kong:
    image: kostkams/kong-jwt-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 30s
      timeout: 10s
      retries: 5